[msbuild]
project = "Pages.sln"

[github]
user = "samdouble"
repo = "pages"
branches = ["master"]

[brew]
publish = false

[changelog]
publish = false

[nuget]
publish = false

[scoop]
publish = false
