version: 2.1

executors:
  my-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: cimg/go:1.16

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet test
            dotnet build
            ls
      - run:
          name: Release
          command: |
            apt update && apt install golang-go -y
            export GOPATH="$HOME/go"
            export PATH="$PATH:$GOPATH/bin"
            go get github.com/github-release/github-release
            github-release release \
              --user samdouble \
              --repo pages \
              --tag v0.1.0 \
              --name "v0.1.0" \
              --pre-release
workflows:
  build-workflow:
    jobs:
      - build
