version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet build
workflows:
  build-workflow:
    jobs:
      - build
