version: 2.1

#orbs: 
#  go: circleci/go@1.7.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      #- go/install:
      #    version: 1.16.5
      - run:
          name: Build
          command: |
            dotnet test
            dotnet build
  release:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run:
          name: Build
          command: |
            go get github.com/github-release/github-release
            github-release --help
workflows:
  build-workflow:
    jobs:
      - build
      - release
