version: 2.1

executors:
  my-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: cimg/go:1.16

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet test
            dotnet build
      - run:
          name: Release
          command: |
            rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            go version
            go get github.com/github-release/github-release
            github-release --help
workflows:
  build-workflow:
    jobs:
      - build
