version: 2.1

orbs: 
  go: circleci/go@1.7.1

jobs:
  build:
    docker:
      #- image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: cimg/go:1.19.0
    steps:
      - checkout
      #- run:
      #    name: Build
      #    command: |
      #      dotnet test
      #      dotnet build
      - run:
          name: Publish a release on GitHub
          command: |
            go get github.com/github-release/github-release
            github-release --help
workflows:
  build-workflow:
    jobs:
      - build
