version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet test
            dotnet build
      - run:
          name: Release
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install --global dotnet-releaser
            dotnet-releaser build dotnet-releaser.toml
            dotnet-releaser publish --force --github-token $GITHUB_TOKEN dotnet-releaser.toml

workflows:
  build-workflow:
    jobs:
      - build
