version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/go:1.16
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet test
            dotnet build
      - run:
          name: Release
          command: |
            go get github.com/github-release/github-release
            github-release --help
workflows:
  build-workflow:
    jobs:
      - build
