name: CI
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'
      - name: Test
        run: |
          dotnet test
      - name: Build
        run: |
          dotnet build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet tool install --global dotnet-releaser
          dotnet-releaser build dotnet-releaser.toml
          dotnet-releaser publish --force --github-token $GITHUB_TOKEN dotnet-releaser.toml
