name: Checks
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'
      - name: Test
        run: |
          dotnet test
      - name: Build
        run: |
          dotnet build
