name: Checks
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Audit
        run: |
          dotnet restore
          dotnet list package --vulnerable --include-transitive
      - name: Test
        run: |
          dotnet test
      - name: Build
        run: |
          dotnet build
